package com.flame.model;

import java.util.Date;
import java.util.List;

import javax.persistence.Transient;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.id
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.domain
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.bucket
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String bucket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_name
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_type
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_size
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.relative_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String relativePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.absolute_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String absolutePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.addition
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private String addition;
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.atime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private Date atime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.mtime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.id
     *
     * @return the value of t_file.id
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.id
     *
     * @param id the value for t_file.id
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.domain
     *
     * @return the value of t_file.domain
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.domain
     *
     * @param domain the value for t_file.domain
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.bucket
     *
     * @return the value of t_file.bucket
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.bucket
     *
     * @param bucket the value for t_file.bucket
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_name
     *
     * @return the value of t_file.file_name
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_name
     *
     * @param fileName the value for t_file.file_name
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_type
     *
     * @return the value of t_file.file_type
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_type
     *
     * @param fileType the value for t_file.file_type
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_size
     *
     * @return the value of t_file.file_size
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_size
     *
     * @param fileSize the value for t_file.file_size
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.relative_path
     *
     * @return the value of t_file.relative_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getRelativePath() {
        return relativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.relative_path
     *
     * @param relativePath the value for t_file.relative_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setRelativePath(String relativePath) {
        this.relativePath = relativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.absolute_path
     *
     * @return the value of t_file.absolute_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getAbsolutePath() {
        return absolutePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.absolute_path
     *
     * @param absolutePath the value for t_file.absolute_path
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setAbsolutePath(String absolutePath) {
        this.absolutePath = absolutePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.addition
     *
     * @return the value of t_file.addition
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public String getAddition() {
        return addition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.addition
     *
     * @param addition the value for t_file.addition
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setAddition(String addition) {
        this.addition = addition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.atime
     *
     * @return the value of t_file.atime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.atime
     *
     * @param atime the value for t_file.atime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setAtime(Date atime) {
        this.atime = atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.mtime
     *
     * @return the value of t_file.mtime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.mtime
     *
     * @param mtime the value for t_file.mtime
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
    
    @Transient
    private  Integer userId;
    
    private  Integer isFile;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getIsFile() {
		return isFile;
	}

	public void setIsFile(Integer isFile) {
		this.isFile = isFile;
	}
	@Transient
	private String fromName;
	@Transient
	private String toName;
	@Transient
	private String fromKey;
	@Transient
	private String toKey;
	@Transient
	private String newFolderName;
	@Transient
	private List<String> fileIds;

	public String getFromName() {
		return fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public String getToName() {
		return toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	public String getFromKey() {
		return fromKey;
	}

	public void setFromKey(String fromKey) {
		this.fromKey = fromKey;
	}

	public String getToKey() {
		return toKey;
	}

	public void setToKey(String toKey) {
		this.toKey = toKey;
	}

	public List<String> getFileIds() {
		return fileIds;
	}

	public void setFileIds(List<String> fileIds) {
		this.fileIds = fileIds;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNewFolderName() {
		return newFolderName;
	}

	public void setNewFolderName(String newFolderName) {
		this.newFolderName = newFolderName;
	}
	
	
    
}