package com.flame.model;

import java.util.Date;

public class Folder {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.folder_name
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private String folderName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.pid
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.permission
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Integer permission;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.user_id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.ctime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Date ctime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_folder.mtime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	private Date mtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.id
	 *
	 * @return the value of t_folder.id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.id
	 *
	 * @param id
	 *            the value for t_folder.id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.folder_name
	 *
	 * @return the value of t_folder.folder_name
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public String getFolderName() {
		return folderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.folder_name
	 *
	 * @param folderName
	 *            the value for t_folder.folder_name
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.pid
	 *
	 * @return the value of t_folder.pid
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.pid
	 *
	 * @param pid
	 *            the value for t_folder.pid
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.permission
	 *
	 * @return the value of t_folder.permission
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Integer getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.permission
	 *
	 * @param permission
	 *            the value for t_folder.permission
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.user_id
	 *
	 * @return the value of t_folder.user_id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.user_id
	 *
	 * @param userId
	 *            the value for t_folder.user_id
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.ctime
	 *
	 * @return the value of t_folder.ctime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.ctime
	 *
	 * @param ctime
	 *            the value for t_folder.ctime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_folder.mtime
	 *
	 * @return the value of t_folder.mtime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public Date getMtime() {
		return mtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_folder.mtime
	 *
	 * @param mtime
	 *            the value for t_folder.mtime
	 *
	 * @mbggenerated Sat Apr 08 14:39:45 CST 2017
	 */
	public void setMtime(Date mtime) {
		this.mtime = mtime;
	}

	private String bucket;

	public String getBucket() {
		return bucket;
	}

	public void setBucket(String bucket) {
		this.bucket = bucket;
	}
	
}