package com.flame.model;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.pid
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.url
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_id
     *
     * @return the value of t_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_id
     *
     * @param menuId the value for t_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_name
     *
     * @return the value of t_menu.menu_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_name
     *
     * @param menuName the value for t_menu.menu_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.pid
     *
     * @return the value of t_menu.pid
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.pid
     *
     * @param pid the value for t_menu.pid
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.url
     *
     * @return the value of t_menu.url
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.url
     *
     * @param url the value for t_menu.url
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.ctime
     *
     * @return the value of t_menu.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.ctime
     *
     * @param ctime the value for t_menu.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.mtime
     *
     * @return the value of t_menu.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.mtime
     *
     * @param mtime the value for t_menu.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}