package com.flame.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.title
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.content
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private String content;
    
    private String userIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.user_name
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.publish_time
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.title
     *
     * @return the value of t_message.title
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.title
     *
     * @param title the value for t_message.title
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.content
     *
     * @return the value of t_message.content
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.content
     *
     * @param content the value for t_message.content
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.user_id
     *
     * @return the value of t_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.user_id
     *
     * @param userId the value for t_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.user_name
     *
     * @return the value of t_message.user_name
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.user_name
     *
     * @param userName the value for t_message.user_name
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.publish_time
     *
     * @return the value of t_message.publish_time
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.publish_time
     *
     * @param publishTime the value for t_message.publish_time
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

	public String getUserIds() {
		return userIds;
	}

	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}
    
    
}