package com.flame.model;

import java.util.Date;

public class Note {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.note_title
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private String noteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.user_id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.ctime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.mtime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_note.content
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.id
     *
     * @return the value of t_note.id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.id
     *
     * @param id the value for t_note.id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.note_title
     *
     * @return the value of t_note.note_title
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public String getNoteTitle() {
        return noteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.note_title
     *
     * @param noteTitle the value for t_note.note_title
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.user_id
     *
     * @return the value of t_note.user_id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.user_id
     *
     * @param userId the value for t_note.user_id
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.ctime
     *
     * @return the value of t_note.ctime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.ctime
     *
     * @param ctime the value for t_note.ctime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.mtime
     *
     * @return the value of t_note.mtime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.mtime
     *
     * @param mtime the value for t_note.mtime
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_note.content
     *
     * @return the value of t_note.content
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_note.content
     *
     * @param content the value for t_note.content
     *
     * @mbggenerated Wed May 03 18:44:17 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}