package com.flame.model;

import java.util.Date;

public class OssFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.bucket
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private String bucket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.file_name
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.file_type
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.file_size
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.oss_key
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private String ossKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.url
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.floder_id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private Integer folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.atime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private Date atime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oss_file.mtime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.id
     *
     * @return the value of t_oss_file.id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.id
     *
     * @param id the value for t_oss_file.id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.bucket
     *
     * @return the value of t_oss_file.bucket
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.bucket
     *
     * @param bucket the value for t_oss_file.bucket
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.file_name
     *
     * @return the value of t_oss_file.file_name
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.file_name
     *
     * @param fileName the value for t_oss_file.file_name
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.file_type
     *
     * @return the value of t_oss_file.file_type
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.file_type
     *
     * @param fileType the value for t_oss_file.file_type
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.file_size
     *
     * @return the value of t_oss_file.file_size
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.file_size
     *
     * @param fileSize the value for t_oss_file.file_size
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.oss_key
     *
     * @return the value of t_oss_file.oss_key
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public String getOssKey() {
        return ossKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.oss_key
     *
     * @param ossKey the value for t_oss_file.oss_key
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setOssKey(String ossKey) {
        this.ossKey = ossKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.url
     *
     * @return the value of t_oss_file.url
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.url
     *
     * @param url the value for t_oss_file.url
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.floder_id
     *
     * @return the value of t_oss_file.floder_id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.floder_id
     *
     * @param folderId the value for t_oss_file.floder_id
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.atime
     *
     * @return the value of t_oss_file.atime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.atime
     *
     * @param atime the value for t_oss_file.atime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setAtime(Date atime) {
        this.atime = atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oss_file.mtime
     *
     * @return the value of t_oss_file.mtime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oss_file.mtime
     *
     * @param mtime the value for t_oss_file.mtime
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}