package com.flame.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_id
     *
     * @return the value of t_role.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_id
     *
     * @param roleId the value for t_role.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.ctime
     *
     * @return the value of t_role.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.ctime
     *
     * @param ctime the value for t_role.ctime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.mtime
     *
     * @return the value of t_role.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.mtime
     *
     * @param mtime the value for t_role.mtime
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}