package com.flame.model;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.role_id
     *
     * @return the value of t_role_menu.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.role_id
     *
     * @param roleId the value for t_role_menu.role_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.menu_id
     *
     * @return the value of t_role_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.menu_id
     *
     * @param menuId the value for t_role_menu.menu_id
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}