package com.flame.model;

public class UserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_message.message_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    private Integer messageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_message.user_id
     *
     * @return the value of t_user_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_message.user_id
     *
     * @param userId the value for t_user_message.user_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_message.message_id
     *
     * @return the value of t_user_message.message_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_message.message_id
     *
     * @param messageId the value for t_user_message.message_id
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
}