package com.flame.model;

public class UserFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_file.user_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_file.file_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_file.permission
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    private Integer permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_file.user_id
     *
     * @return the value of t_user_file.user_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_file.user_id
     *
     * @param userId the value for t_user_file.user_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_file.file_id
     *
     * @return the value of t_user_file.file_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_file.file_id
     *
     * @param fileId the value for t_user_file.file_id
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_file.permission
     *
     * @return the value of t_user_file.permission
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_file.permission
     *
     * @param permission the value for t_user_file.permission
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
}