package com.flame.dao;

import java.util.List;
import java.util.Map;

import com.flame.model.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Mon Apr 03 09:27:34 CST 2017
     */
    int updateByPrimaryKey(File record);
    int deleteUserFile(File record);
    int deleteFile(File record);
    List<String> listUserFileIds(File record);
    List<Map<String,Object>> listFolders(File record);
    List<Map<String,Object>> listFiles(File record);
    int reNameObject(File record);
}