package com.flame.dao;

import java.util.List;
import java.util.Map;

import com.flame.model.OssFile;

public interface OssFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    int insert(OssFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    int insertSelective(OssFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    OssFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    int updateByPrimaryKeySelective(OssFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oss_file
     *
     * @mbggenerated Sat Apr 08 14:31:20 CST 2017
     */
    int updateByPrimaryKey(OssFile record);
    int deleteByFolderId(Integer floderId);
    List<Map<String,Object>> queryByFolderId(Integer floderId);
}