package com.flame.dao;

import com.flame.model.RoleMenu;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insertSelective(RoleMenu record);
}