package com.flame.dao;

import java.util.List;

import com.flame.model.SysLog;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    SysLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Sun Apr 09 16:02:33 CST 2017
     */
    int updateByPrimaryKey(SysLog record);
    List<SysLog> queryForList();
}