package com.flame.dao;

import com.flame.model.UserMessage;

public interface UserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    int insert(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbggenerated Mon May 08 10:13:47 CST 2017
     */
    int insertSelective(UserMessage record);
    int deleteByMessageId(Integer messageId);
}