package com.flame.dao;

import com.flame.model.UserFile;

public interface UserFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_file
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    int insert(UserFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_file
     *
     * @mbggenerated Sun Apr 02 23:16:16 CST 2017
     */
    int insertSelective(UserFile record);
}