package com.flame.dao;

import com.flame.model.UserQuestion;
import java.util.List;

public interface UserQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_question
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insert(UserQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_question
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insertSelective(UserQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_question
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    
    /**
     * @param record
     * @return
     */
    UserQuestion  findUserQuestion(UserQuestion record);
}