package com.flame.dao;

import java.util.List;
import java.util.Map;

import com.flame.model.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbggenerated Wed Mar 29 11:09:16 CST 2017
	 */
	int updateByPrimaryKey(User record);

	/**
	 * 查询用户列表
	 * @return
	 */
	List<User> queryForList();

	/**
	 * 查询用户角色
	 * @param userId
	 * @return
	 */
	List<Map> queryRoleByUserId(Integer userId);
	/**
	 * 查询问题列表
	 * @return
	 */
	List<Map> queryQuestionList();
	
	/**
	 * 查询用户
	 * @param userName
	 * @return
	 */
	User findUserByUserName(String userName);
	
	/**
	 * 查询角色权限菜单
	 * @param roleId
	 * @return
	 */
	List<Map> queryMenuByRoleId(Integer roleId);
}