package com.flame.dao;

import com.flame.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Thu Mar 30 00:28:05 CST 2017
     */
    int insertSelective(UserRole record);
}